edit_uri: https://github.com/CCMS-UCSD/GNPSDocumentation/blob/master/docs/
nav:
- Hydroxy acids and derivatives.md: Hydroxy acids and derivatives.md
- Furanoid lignans.md: Furanoid lignans.md
- Anthracenes.md: Anthracenes.md
- Tetrapyrroles and derivatives.md: Tetrapyrroles and derivatives.md
- Purine nucleosides.md: Purine nucleosides.md
- Emetine alkaloids.md: Emetine alkaloids.md
- Diazanaphthalenes.md: Diazanaphthalenes.md
- Fatty Acyls.md: Fatty Acyls.md
- nan.md: nan.md
- Azaphilones.md: Azaphilones.md
- Benzazepines.md: Benzazepines.md
- Imidazopyrimidines.md: Imidazopyrimidines.md
- Isobenzofurans.md: Isobenzofurans.md
- Kavalactones.md: Kavalactones.md
- Dibenzocycloheptenes.md: Dibenzocycloheptenes.md
- Purine nucleotides.md: Purine nucleotides.md
- Diazines.md: Diazines.md
- Quinolines and derivatives.md: Quinolines and derivatives.md
- Indenes and isoindenes.md: Indenes and isoindenes.md
- Steroids and steroid derivatives.md: Steroids and steroid derivatives.md
- Morphinans.md: Morphinans.md
- Coumarans.md: Coumarans.md
- Dithiolanes.md: Dithiolanes.md
- Benzoxepines.md: Benzoxepines.md
- Cinnamaldehydes.md: Cinnamaldehydes.md
- Triazines.md: Triazines.md
- Coumarins and derivatives.md: Coumarins and derivatives.md
- Benzodioxoles.md: Benzodioxoles.md
- Linear 1,3-diarylpropanoids.md: Linear 1,3-diarylpropanoids.md
- Saccharolipids.md: Saccharolipids.md
- Depsides and depsidones.md: Depsides and depsidones.md
- Organic phosphoric acids and derivatives.md: Organic phosphoric acids and derivatives.md
- Lignan lactones.md: Lignan lactones.md
- Stilbenes.md: Stilbenes.md
- Piperidines.md: Piperidines.md
- Naphthofurans.md: Naphthofurans.md
- Pyrans.md: Pyrans.md
- 2-arylbenzofuran flavonoids.md: 2-arylbenzofuran flavonoids.md
- Benzimidazoles.md: Benzimidazoles.md
- Thiadiazinanes.md: Thiadiazinanes.md
- Prenol lipids.md: Prenol lipids.md
- Tannins.md: Tannins.md
- Arylnaphthalene lignans.md: Arylnaphthalene lignans.md
- Naphthopyrans.md: Naphthopyrans.md
- Phthalide isoquinolines.md: Phthalide isoquinolines.md
- Oxazinanes.md: Oxazinanes.md
- Isoquinolines and derivatives.md: Isoquinolines and derivatives.md
- Organooxygen compounds.md: Organooxygen compounds.md
- Glycerophospholipids.md: Glycerophospholipids.md
- Keto acids and derivatives.md: Keto acids and derivatives.md
- Isoflavonoids.md: Isoflavonoids.md
- Organic sulfuric acids and derivatives.md: Organic sulfuric acids and derivatives.md
- Benzodiazepines.md: Benzodiazepines.md
- Aurone flavonoids.md: Aurone flavonoids.md
- Azoles.md: Azoles.md
- Phenol ethers.md: Phenol ethers.md
- Organonitrogen compounds.md: Organonitrogen compounds.md
- Flavonoids.md: Flavonoids.md
- Cinchona alkaloids.md: Cinchona alkaloids.md
- Benzothiazepines.md: Benzothiazepines.md
- Angucyclines.md: Angucyclines.md
- Isocoumarins and derivatives.md: Isocoumarins and derivatives.md
- Benzene and substituted derivatives.md: Benzene and substituted derivatives.md
- Aryltetralin lignans.md: Aryltetralin lignans.md
- Organic thiophosphoric acids and derivatives.md: Organic thiophosphoric acids and
    derivatives.md
- Phenylpropanoic acids.md: Phenylpropanoic acids.md
- Diarylheptanoids.md: Diarylheptanoids.md
- Yohimbine alkaloids.md: Yohimbine alkaloids.md
- Indanes.md: Indanes.md
- Glycerolipids.md: Glycerolipids.md
- Peptidomimetics.md: Peptidomimetics.md
- Carboxylic acids and derivatives.md: Carboxylic acids and derivatives.md
- Phenols.md: Phenols.md
- Polypeptides.md: Polypeptides.md
- Pyrroles.md: Pyrroles.md
- Macrolactams.md: Macrolactams.md
- Oxepanes.md: Oxepanes.md
- Pyridines and derivatives.md: Pyridines and derivatives.md
- Lactones.md: Lactones.md
- Benzothiazines.md: Benzothiazines.md
- 5'-deoxyribonucleosides.md: 5'-deoxyribonucleosides.md
- Furopyridines.md: Furopyridines.md
- Carboximidic acids and derivatives.md: Carboximidic acids and derivatives.md
- Triphenyl compounds.md: Triphenyl compounds.md
- Protopine alkaloids.md: Protopine alkaloids.md
- Benzofurans.md: Benzofurans.md
- Pteridines and derivatives.md: Pteridines and derivatives.md
- Lignan glycosides.md: Lignan glycosides.md
- Ergoline and derivatives.md: Ergoline and derivatives.md
- Biotin and derivatives.md: Biotin and derivatives.md
- Organic dithiophosphoric acids and derivatives.md: Organic dithiophosphoric acids
    and derivatives.md
- Protoberberine alkaloids and derivatives.md: Protoberberine alkaloids and derivatives.md
- Macrolides and analogues.md: Macrolides and analogues.md
- Isoindoles and derivatives.md: Isoindoles and derivatives.md
- Indoles and derivatives.md: Indoles and derivatives.md
- Neoflavonoids.md: Neoflavonoids.md
- Phenanthrenes and derivatives.md: Phenanthrenes and derivatives.md
- Endocannabinoids.md: Endocannabinoids.md
- Naphthalenes.md: Naphthalenes.md
- Aporphines.md: Aporphines.md
- Rhoeadine alkaloids.md: Rhoeadine alkaloids.md
- Tetralins.md: Tetralins.md
- Benzoxazines.md: Benzoxazines.md
- Organometalloid compounds.md: Organometalloid compounds.md
- Diazinanes.md: Diazinanes.md
- Pyrimidine nucleotides.md: Pyrimidine nucleotides.md
- Pyrimidine nucleosides.md: Pyrimidine nucleosides.md
- Dibenzylbutane lignans.md: Dibenzylbutane lignans.md
- Benzopyrans.md: Benzopyrans.md
plugins:
- search
repo_name: CCMS-UCSD/GNPSDocumentation
repo_url: https://github.com/CCMS-UCSD/GNPSDocumentation
site_name: GNPS Documentation
site_url: https://ccms-ucsd.github.io/GNPSDocumentation/
theme:
  name: material
